import Link from "next/link";
import { ArrowRight } from "lucide-react";
import NotConnected from "@/components/NotConnected";
import RequestReport from "@/components/RequestReport";
import { Card, CardHeader, PageHeader, Status } from "@/components/ui";
import { ctx } from "@/lib/data";
import { monthLabel, shortDateTime } from "@/lib/format";

export const dynamic = "force-dynamic";

// Signed monthly statements of what the gateway observed for this firm:
// counts only, from the gateway's own records, nothing the firm entered.
export default async function ReportsPage() {
  const c = await ctx();
  if (!c.gw) return <><PageHeader title="Reports" /><NotConnected /></>;
  const reports = await c.gw.reports();
  const thisMonth = new Date().toISOString().slice(0, 7);
  return (
    <>
      <PageHeader title="Reports" sub="One signed statement per month: accounts read, coverage, verdicts, payout checks, linked accounts and ledger integrity. For certification bodies, auditors and your own marketing."><RequestReport period={thisMonth} /></PageHeader>
      <Card>
        <CardHeader title="Monthly reports" tip="Generated by the gateway on the 1st of each month from its own records and signed like every other record. Nothing you enter in this console affects a report, so it means the same for every firm. A report for the current month is marked partial and is replaced by the final one." />
        {reports.length === 0 ? <div className="px-5 py-10 text-center text-muted">No report yet. The first is generated on the 1st of next month; use the button above for the month so far.</div> : (
          <div className="overflow-x-auto"><table className="w-full border-collapse">
            <thead><tr><th className="th">Period</th><th className="th">Status</th><th className="th hidden md:table-cell">Generated</th><th className="th hidden lg:table-cell">Hash</th><th className="th" /></tr></thead>
            <tbody>{reports.map((r) => (
              <tr key={r.id}>
                <td className="td"><Link href={`/app/reports/${r.id}`} className="font-semibold hover:text-accent">{monthLabel(r.period.from)}</Link></td>
                <td className="td">{r.period.partial ? <Status tone="pend">Month so far</Status> : <Status tone="ok">Final</Status>}</td>
                <td className="td whitespace-nowrap hidden md:table-cell">{shortDateTime(r.generated_at)} UTC</td>
                <td className="td mono text-xs hidden lg:table-cell">{r.body_hash.slice(0, 20)}…</td>
                <td className="td text-right"><Link href={`/app/reports/${r.id}`} className="btn btn-sm">Open<ArrowRight className="h-3.5 w-3.5" /></Link></td>
              </tr>
            ))}</tbody>
          </table></div>
        )}
      </Card>
    </>
  );
}
